name: Build
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TOOLCHAIN_URI: "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/a71fa4c09d7109d611ee63964fc9fca58fee38cd/clang-r450784d.tar.gz"
      ARCH: arm64
      LLVM: 1
      LLVM_IAS: 1

    steps:
      - uses: actions/checkout@v7
        with:
         path: toolchain
         key: toolchain-${{ env.TOOLCHAIN_URI }}
      - name: Get toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          mkdir --parents toolchain/clang/host/linux-x86
          curl --silent "${{ env.TOOLCHAIN_URI }}" | tar --extract --directory=toolchain/clang/host/linux-x86 --gzip

      - name: Setup toolchain path
        run: echo "${{ github.workspace }}/toolchain/clang/host/linux-x86/bin" >> $GITHUB_PATH

      - name: Build
        run: |
         make O=out exynos9830_defconfig
         make O=out r8s.config
         make O=out --jobs=$(nproc --all)
    
      - name: get AnyKernel3
        run: git clone https://github.com/redmax19/AnyKernel3

      - name: Build AnyKernel package
        run: |
          cp arch/arm64/boot/Image AnyKernel3/Image
          cat << 'EOF' > AnyKernel3/anykernel.sh
          ### AnyKernel3 Ramdisk Mod Script
          ## osm0sis @ xda-developers

          ### AnyKernel setup
          # global properties
          properties() { '
          kernel.string=kernel_r8s
          do.devicecheck=1
          do.modules=0
          do.systemless=1
          do.cleanup=1
          do.cleanuponabort=0
          device.name1=r8s
          device.name2=
          device.name3=
          device.name4=
          device.name5=
          supported.versions=
          supported.patchlevels=
          supported.vendorpatchlevels=
          '; } # end properties

          ### AnyKernel install
          # boot shell variables
          block=/dev/block/by-name/boot;
          is_slot_device=0;
          ramdisk_compression=auto;
          patch_vbmeta_flag=auto;

          # import functions/variables and setup patching - see for reference (DO NOT REMOVE)
          . tools/ak3-core.sh;

          # boot install
          dump_boot; # use split_boot to skip ramdisk unpack, e.g. for devices with init_boot ramdisk

          write_boot; # use flash_boot to skip ramdisk repack, e.g. for devices with init_boot ramdisk
          ## end boot install
          EOF

          cd AnyKernel3
          zip -r9 "../kernel-r8s.zip" * -x .git .github README.md *placeholder

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kernel-r8s.zip
          name: Kernel r8s - ${{ github.run_id }}
          tag_name: build-${{ github.run_id }}
          body: |
            ## Kernel  Build

            Device:
            - Samsung r8s

            Commit:
            ${{ github.sha }}
